description = "Static base image (Ubuntu Jammy Jellyfish build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/build-jammy-static:0.0.159"

[lifecycle]
  version = "0.20.14"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/run-jammy-static:latest"

[stack]
  id = "io.buildpacks.stacks.jammy.static"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
