description = "Static base image (Ubuntu Jammy Jellyfish build image, distroless-like run image) with no buildpacks included. To use, specify buildpacks at build time."

[lifecycle]
  version = "0.16.5"

[stack]
  build-image = "docker.io/paketobuildpacks/build-jammy-static:0.0.54"
  id = "io.buildpacks.stacks.jammy.static"
  run-image = "index.docker.io/paketobuildpacks/run-jammy-static:latest"
  run-image-mirrors = []
